/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUserRouteImport } from './routes/_authed/user'
import { Route as AuthedStudiosRouteImport } from './routes/_authed/studios'
import { Route as AuthedStudiosStudioIdRouteImport } from './routes/_authed/studios_.$studioId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUserRoute = AuthedUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudiosRoute = AuthedStudiosRouteImport.update({
  id: '/studios',
  path: '/studios',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudiosStudioIdRoute = AuthedStudiosStudioIdRouteImport.update({
  id: '/studios_/$studioId',
  path: '/studios/$studioId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studios': typeof AuthedStudiosRoute
  '/user': typeof AuthedUserRoute
  '/studios/$studioId': typeof AuthedStudiosStudioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studios': typeof AuthedStudiosRoute
  '/user': typeof AuthedUserRoute
  '/studios/$studioId': typeof AuthedStudiosStudioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/studios': typeof AuthedStudiosRoute
  '/_authed/user': typeof AuthedUserRoute
  '/_authed/studios_/$studioId': typeof AuthedStudiosStudioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/studios' | '/user' | '/studios/$studioId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studios' | '/user' | '/studios/$studioId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/studios'
    | '/_authed/user'
    | '/_authed/studios_/$studioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/user': {
      id: '/_authed/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthedUserRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/studios': {
      id: '/_authed/studios'
      path: '/studios'
      fullPath: '/studios'
      preLoaderRoute: typeof AuthedStudiosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/studios_/$studioId': {
      id: '/_authed/studios_/$studioId'
      path: '/studios/$studioId'
      fullPath: '/studios/$studioId'
      preLoaderRoute: typeof AuthedStudiosStudioIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedStudiosRoute: typeof AuthedStudiosRoute
  AuthedUserRoute: typeof AuthedUserRoute
  AuthedStudiosStudioIdRoute: typeof AuthedStudiosStudioIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedStudiosRoute: AuthedStudiosRoute,
  AuthedUserRoute: AuthedUserRoute,
  AuthedStudiosStudioIdRoute: AuthedStudiosStudioIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
